version: "3.8"
services:
  app:
    build: .
    container_name: client-service
    env_file:
      - .env
    environment:
      - NATS_URL=${NATS_URL}
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    networks:
      - my_shared_network

networks:
  my_shared_network:
    external: true